---


- name: Update repositories cache
  become: yes
  apt:
    update_cache: yes


- name: Install indi development packages
  become: yes
  package:
    name: "{{ indi_packages }}"
    state: present
