---


- name: Install EPEL on CentOS
  become: yes
  package:
    name:
      - epel-release
    state: present
  when:
    - ansible_facts['distribution'] == 'CentOS'


- name: Install indi development packages
  become: yes
  package:
    name: "{{ indi_packages }}"
    state: present
    enablerepo:
      - PowerTools
      - powertools
