---
services:
  indi.base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indi_base_debian12
      #dockerfile: docker/Dockerfile.indi_base_ubuntu2204
      args:
        - TZ=${TZ}
        - INDI_VERSION=${INDIALLSKY_INDI_VERSION}
        - LIBCAMERA_TAG=${INDIALLSKY_LIBCAMERA_TAG}
        - RPICAM_APPS_TAG=${INDIALLSKY_RPICAM_APPS_TAG}
    env_file: .env


  mariadb.indi.allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mariadb
    env_file: .env
    volumes:
      - database_indi_allsky:/var/lib/mysql
    ports:
      - "13306:3306"


  indiserver.indi.allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indiserver_debian12
      #dockerfile: docker/Dockerfile.indiserver_ubuntu2204
      args:
        - INDI_VERSION=${INDIALLSKY_INDI_VERSION}
        - INDI_CAMERA_VENDOR=${INDIALLSKY_CAMERA_VENDOR}
    env_file: .env
    depends_on:
      - indi.base
    privileged: true
    ports:
      - "17624:7624"


  gunicorn.indi.allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gunicorn
    env_file: .env
    depends_on:
      - mariadb.indi.allsky
    volumes:
      - images_indi_allsky:/var/www/html/allsky
      - migrations_indi_allsky:/var/lib/indi-allsky
  #  ports:
  #    - "8000:8000"


  capture.indi.allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.capture
    env_file: .env
    depends_on:
      - indi.base
      - mariadb.indi.allsky
      - indiserver.indi.allsky
    #privileged: true  # enable for libcamera
    volumes:
      - images_indi_allsky:/var/www/html/allsky
      #- /run/udev:/run/udev:ro  # enable for libcamera


  webserver.indi.allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.webserver_apache
      #dockerfile: docker/Dockerfile.webserver_nginx
      args:
        - INDIALLSKY_IMAGE_FOLDER=${INDIALLSKY_IMAGE_FOLDER}
    env_file: .env
    depends_on:
      - gunicorn.indi.allsky
    volumes:
      - images_indi_allsky:/var/www/html/allsky
    ports:
      - "8080:80"
      - "8443:443"


  mosquitto.indi.allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mosquitto
      args:
        - MOSQUITTO_USER=${INDIALLSKY_MOSQUITTO_USER}
        - MOSQUITTO_PASS=${INDIALLSKY_MOSQUITTO_PASS}
    env_file: .env
    volumes:
      - mosquitto_data_indi_allsky:/mosquitto/data
    ports:
      - "18883:8883"
      - "18081:8081"


volumes:
  database_indi_allsky:
  migrations_indi_allsky:
  images_indi_allsky:
  mosquitto_data_indi_allsky:
